CaterCroweCapstone2019Admin/Models/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CaterCroweCapstone2019Admin.Models
{
    public class Course
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int TeacherId { get; set; }
        public int MaxSeats { get; set; }
        public int RemainingSeats { get; set; }
        public int SemesterId { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Location { get; set; }
        public int RoomNumber { get; set; }
        public string DaysOfWeek { get; set; }
        public List<Prereq> Prereqs { get; set; }

    }
}

CaterCroweCapstone2019Admin/Controllers/CourseController.cs
using CaterCroweCapstone2019Admin.Models;
using CaterCroweCapstone2019Admin.Models.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaterCroweCapstone2019Admin.Controllers
{
    public class CourseController : Controller
    {
        private CourseDAL courseDAL;
        private UserDAL userDAL;

        public CourseController()
        {
            this.courseDAL = new CourseDAL();
            this.userDAL = new UserDAL();
        }

        public ActionResult Portal()
        {
            var teacherSelectItems = new List<SelectListItem>();

            foreach (var currentTeacher in this.userDAL.GetAllTeachers())
            {
                teacherSelectItems.Add(new SelectListItem(){ Value = currentTeacher.TeacherId.ToString(), Text = currentTeacher.Username });
            }

            var coursesSelectItems = new List<SelectListItem>();

            foreach (var course in this.courseDAL.GetAllCourses())
            {
                coursesSelectItems.Add(new SelectListItem()
                {
                    Text = course.Name,
                    Value = course.Id.ToString()
                });
            }

            ViewBag.Teachers = new SelectList(teacherSelectItems, "Value", "Text");
            ViewBag.Courses = new SelectList(coursesSelectItems, "Value", "Text");

            return View("Portal");
        }

        [HttpPost]
        public ActionResult Create(Course course)
        {
            try
            {
                var courseID = this.courseDAL.CreateCourse(course);

                this.courseDAL.InsertPrereqsForCourse(courseID, course.Prereqs);
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;
            }

            return RedirectToAction("Portal");
        }

        [HttpPost]
        public ActionResult Edit(Course course)
        {
            try
            {
                this.courseDAL.EditCourse(course);

                var dbPrereqs = this.courseDAL.GetCoursePrereqsByCourseId(course.Id);

                var prereqEdits = new List<Prereq>();
                var prereqNews = new List<Prereq>();

                foreach (var dbPrereq in dbPrereqs)
                {
                    var hasCourse = false;
                    foreach (var coursePrereq in course.Prereqs)
                    {
                        if (dbPrereq.PrereqId == coursePrereq.PrereqId)
                        {
                            hasCourse = true;
                            prereqEdits.Add(coursePrereq);
                        }
                    }

                    if (!hasCourse)
                    {
                        this.courseDAL.DropPrereqFromCourse(course.Id, dbPrereq.PrereqId);
                    }
                }

                foreach (var coursePrereq in course.Prereqs)
                {
                    if (!prereqEdits.Contains(coursePrereq))
                    {
                        prereqNews.Add(coursePrereq);
                    }
                }

                this.courseDAL.InsertPrereqsForCourse(course.Id, prereqNews);
                this.courseDAL.UpdatePrereqsForCourseId(course.Id, prereqEdits);
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;
            }

            return RedirectToAction("Portal");
        }

        #region Request Handling 

        [HttpGet]
        public JsonResult GetCourseByID(int courseID)
        {
            var course = this.courseDAL.GetCourseById(courseID);
            course.Prereqs = this.courseDAL.GetCoursePrereqsByCourseId(courseID);

            return Json(course, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

CaterCroweCapstone2019Admin/Views/Course/Portal.cshtml
@model CaterCroweCapstone2019Admin.Models.Course

@{
    ViewBag.Title = "Portal";
}

@Scripts.Render("~/Scripts/CourseManipulation.js")

<h2>Portal</h2>

<hr />
<select id="form-select" class="form-control dropdown">
    <option value="Create">Create</option>
    <option value="Edit">Edit</option>
</select>
<hr />

@using (Html.BeginForm("Create", "Course", FormMethod.Post, new { @id = "Create-Form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.Label("Selected Teacher", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", (SelectList)ViewBag.Teachers, new { @class = "form-control dropdown" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxSeats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxSeats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxSeats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RemainingSeats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RemainingSeats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RemainingSeats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SemesterId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SemesterId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SemesterId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaysOfWeek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DaysOfWeek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DaysOfWeek, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.DropDownList("Create-Prereq-Selection", (SelectList)ViewBag.Courses)
            <input type="button" id="add-row-create-prereqs" value="Add Row"/>
            <table class="table table-active" id="create-course-prereqs">
                <thead>
                <tr>
                    <th>Course</th>
                    <th>Required Grade</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                <input type="button" id="clear-create-button" value="Clear" class="btn btn-dark" />
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("Edit", "Course", FormMethod.Post, new { @id = "Edit-Form", @hidden = "hidden" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit</h4>
        <hr />
        <div class="form-group">
            <div class="col-md-10">
                <input type="number" id="selected-class-id" class="form-control" />
                <input type="button" id="select-class-button" class="btn btn-outline-secondary" value="Select Class" />
            </div>
        </div>
        <hr />
        <div id="edit-form-content" hidden>
        @Html.HiddenFor(model => model.TeacherId)
        @Html.HiddenFor(model => model.Id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaxSeats, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaxSeats, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaxSeats, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group">
                @Html.Label("Selected Teacher", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TeacherId", (SelectList)ViewBag.Teachers, new { @class = "form-control dropdown" })
                </div>
            </div>

            <div class="form-group">
            @Html.LabelFor(model => model.RemainingSeats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RemainingSeats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RemainingSeats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SemesterId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SemesterId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SemesterId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaysOfWeek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DaysOfWeek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DaysOfWeek, "", new { @class = "text-danger" })
            </div>
        </div>  
            
        <div class="form-group">
            @Html.DropDownList("Edit-Prereq-Selection", (SelectList)ViewBag.Courses)
            <input type="button" id="add-row-edit-prereqs" value="Add Row"/>
            <table class="table table-active" id="edit-course-prereqs">
                <thead>
                <tr>
                    <th>Course</th>
                    <th>Required Grade</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
            
            <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-primary" />
                <input type="button" id="clear-edit-button" value="Clear" class="btn btn-dark" />
            </div>
        </div>
        </div>
    </div>
}

<p class="error"></p>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>