CaterCroweCapstone2019/Models/DAL/DALModels/GradeItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CaterCroweCapstone2019.Models.DAL.DALModels
{
    public class GradeItem
    {
        #region Data Members
        private int id;
        private string name;
        private string description;
        private int maxGrade;
        private int weightType;
        private DateTime dueDate;
        private int courseID;
        private int studentID;
        private double grade;
        #endregion

        #region Properties
        /// <summary>
        /// Gets and sets the Id for the GradeItem.
        /// </summary>
        /// <exception cref="System.ArgumentException">Id must be >= 0</exception>
        /// <return>Returns the value of id.</return>
        public int ID {
            get
            {
                return this.id;
            }
            set
            {
                if(value < 0)
                {
                    throw new ArgumentException("Id cannot be less than zero.");
                }
                this.id = value;
            }
        }

        /// <summary>
        /// Gets and sets the Name for the GradeItem.
        /// </summary>
        /// <exception cref="System.ArgumentException">Name cannot be null or empty string.</exception>
        /// <return>Returns the value of Name.</return>
        public string Name {
            get
            {
                return this.name;
            }
            set
            {
                if (String.IsNullOrEmpty(value))
                {
                    throw new ArgumentException("Name cannot be null or empty.");
                }
                this.name = value;
            }
        }

        /// <summary>
        /// Gets and sets the Description for the GradeItem.
        /// </summary>
        /// <return>Returns the value of Description.</return>
        public string Description {
            get
            {
                return this.description;
            }
            set
            {
                this.description = value;
            }
        }

        /// <summary>
        /// Gets and sets the Max Grade for the GradeItem.
        /// </summary>
        /// <exception cref="System.ArgumentException">Max Grade must be >= 0.0</exception>
        /// <return>Returns the value of the Max Grade.</return>
        public int MaxGrade {
            get
            {
                return this.maxGrade;
            }
            set
            {
                if(value <= 0)
                {
                    throw new ArgumentException("Max Grade cannot be less than zero.");
                }
                this.maxGrade = value;
            }
        }

        /// <summary>
        /// Gets and sets the Weight Type for the GradeItem.
        /// </summary>
        /// <exception cref="System.ArgumentException">Weight Type must be >= 0</exception>
        /// <return>Returns the value of the Weight Type.</return>
        public int WeightType {
            get
            {
                return this.weightType;
            }
            set
            {
                if(value < 0)
                {
                    throw new ArgumentException("Weight type cannot be less than zero.");
                }
                this.weightType = value;
            }
        }

        /// <summary>
        /// Get and sets the due date for the grade item.
        /// </summary>
        /// <exception cref="System.ArgumentException">Due Date cannot be null.</exception>
        /// <return>Returns the date and time the grade item is due.</return>
        public DateTime DueDate
        {
            get
            {
                return this.dueDate;
            }
            set
            {
                if (value == null)
                {
                    throw new ArgumentException("Due date cannot be null.");
                }
                this.dueDate = value;
            }
        }

        /// <summary>
        /// Gets and set the Course Id for the GradeItem.
        /// </summary>
        /// <exception cref="System.ArgumentException">CourseId must be >= 0</exception>
        /// <return>Returns the value of Course Id.</return>
        public int CourseID
        {
            get
            {
                return this.courseID;
            }
            set
            {
                if (value < 0)
                {
                    throw new ArgumentException("Course Id cannot be less than zero.");
                }
                this.courseID = value;
            }

        }

        /// <summary>
        /// Gets and sets the Student Id for the GradeItem.
        /// </summary>
        /// <exception cref="System.ArgumentException">Student Id must be >= 0</exception>
        /// <return>Returns the value of Student Id.</return>
        public int StudentID
        {
            get
            {
                return this.studentID;
            }
            set
            {
                if (value < 0)
                {
                    throw new ArgumentException("Student Id cannot be less than zero.");
                }
                this.studentID = value;
            }
        }

        /// <summary>
        /// Gets and sets the grade for the grade item.
        /// </summary>
        /// <exception cref="System.ArgumentException">Grade must be >= 0</exception>
        /// <return>Returns the grade achieved for the grade item.</return>
        public double Grade
        {
            get
            {
                return this.grade;
            }
            set
            {
                if (value < 0)
                {
                    throw new ArgumentException("Grade cannot be less than zero.");
                }
                this.grade = value;
            }
        }
        #endregion
    }
}

CaterCroweCapstone2019/Controllers/GradeItemController.cs
using CaterCroweCapstone2019.Models.DAL;
using CaterCroweCapstone2019.Models.DAL.DALModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaterCroweCapstone2019.Controllers
{
    public class GradeItemController : Controller
    {
        private GradeItemDAL DAL = new GradeItemDAL();
        private RubricDAL RubricDAL = new RubricDAL();
        private WeightTypeDAL WeightTypeDAL = new WeightTypeDAL();

        // GET: GradeItem
        public ActionResult Index()
        {
            //var gradeItems = this.DAL.GetAllGradeItems();

            //var rubric = this.RubricDAL.getRubricByCourseId(1);

            //var gradeAmounts = new Dictionary<int, double>();
            //var gradeCounts = new Dictionary<int, int>();
            //var weightTypes = this.WeightTypeDAL.getWeightTypes();

            //var maxPoints = 0.0;

            //foreach (var current in rubric.RubricValues)
            //{
            //    maxPoints += current.Value;
            //}

            //foreach (var item in gradeItems)
            //{
            //    if (!gradeAmounts.Keys.Contains(item.WeightType))
            //    {
            //        gradeAmounts.Add(item.WeightType, item.Grade);
            //        gradeCounts.Add(item.WeightType, 1);
            //    }
            //    else
            //    {
            //        gradeAmounts[item.WeightType] += item.Grade;
            //        gradeCounts[item.WeightType]++;
            //    }
            //}

            //var total = 0.0;

            //foreach (var index in gradeAmounts.Keys)
            //{
            //    total += gradeAmounts[index] / Convert.ToDouble(gradeCounts[index]) * (rubric.RubricValues[weightTypes[index]] / maxPoints);
            //}

            //ViewBag.totalGrade = total;

            //return View("Index", gradeItems);
            return View("Index");
        }

        // GET: GradeItem/Details/5
        public ActionResult Details(int id)
        {
            var gradeItem = this.DAL.GetGradeItemByID(id);

            return View("Details", gradeItem);
        }

        // GET: GradeItem/Create
        public ActionResult Create()
        {
            ViewBag.weightTypes = new SelectList(this.WeightTypeDAL.getWeightTypes(), "key", "value");

            return View("Create");
        }

        // POST: GradeItem/Create
        [HttpPost]
        public ActionResult Create(GradeItem gradeItem)
        {
            try
            { 
                var result = this.DAL.insertGradeItem(gradeItem);

                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                return View("Create");
            }
        }

        // GET: GradeItem/Edit/5
        public ActionResult Edit(int id)
        {
            var gradeItem = this.DAL.GetGradeItemByID(id);
            ViewBag.weightTypes = new SelectList(this.WeightTypeDAL.getWeightTypes(), "key", "value", gradeItem.WeightType);

            return View("Edit", gradeItem);
        }

        // POST: GradeItem/Edit/5
        [HttpPost]
        public ActionResult Edit(GradeItem gradeItem)
        {
            try
            {
                var result = this.DAL.UpdateGradeItem(gradeItem);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Edit");
            }
        }

        // GET: GradeItem/Delete/5
        public ActionResult Delete(int id)
        {
            return View("Delete");
        }

        // POST: GradeItem/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Delete");
            }
        }
    }
}

CaterCroweCapstone2019/Views/GradeItem/Create.cshtml
@model CaterCroweCapstone2019.Models.DAL.DALModels.GradeItem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GradeItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WeightType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WeightType",(SelectList)ViewBag.weightTypes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WeightType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CaterCroweCapstone2019/Views/GradeItem/Details.cshtml
@model CaterCroweCapstone2019.Models.DAL.DALModels.GradeItem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>GradeItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WeightType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WeightType)
        </dd>

    </dl>
</div>
<p>
    @if (@Session["role"] != null && Convert.ToString(Session["role"]).Equals("teacher"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) <br />
    }
    @Html.ActionLink("Back to List", "Index")
</p>

CaterCroweCapstone2019/Views/GradeItem/Edit.cshtml
@model CaterCroweCapstone2019.Models.DAL.DALModels.GradeItem


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GradeItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WeightType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WeightType", (SelectList)ViewBag.weightTypes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WeightType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CaterCroweCapstone2019/Views/GradeItem/Index.cshtml
@model List<CaterCroweCapstone2019.Models.DAL.DALModels.GradeItem>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table table-active">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Grade</th>
            <th>Type</th>
            @if (@Session["role"] != null && Convert.ToString(Session["role"]).Equals("teacher"))
            {
                <th>@Html.ActionLink("Create", "Create", "GradeItem", null, new { @class = "btn btn-primary" })</th>
            }
            </tr>
    </thead>
    <tbody>
        @foreach (var currentGradeItem in Model)
        {
            <tr>
                <td>@currentGradeItem.Name</td>
                <td>@currentGradeItem.Description</td>
                <td>@currentGradeItem.Grade</td>
                <td>@currentGradeItem.WeightType</td>
                <td>
                @if (@Session["role"] != null && Convert.ToString(Session["role"]).Equals("teacher"))
                {
                    @Html.ActionLink("Edit", "Edit", "GradeItem", new { @id = currentGradeItem.ID }, new { @class = "btn btn-primary" })
                }
                @Html.ActionLink("Details", "Details", "GradeItem", new { @id = currentGradeItem.ID}, new { @class = "btn btn-secondary" })
                </td>
            </tr>
        }
    </tbody>
</table>

<h2>Total Grade: @ViewBag.totalGrade</h2>